#pragma once


#ifdef PLAYER_US
const uint8_t * const player_images[] PROGMEM = { p38_0, p38_1, p38_2, p38_3, p38_4, p38_3, p38_6, p38_1, p38_mask_0, p38_mask_1, p38_mask_2, p38_mask_3, p38_mask_4, p38_mask_3, p38_mask_6, p38_mask_1, explosion_01, explosion_02, explosion_03, explosion_04, explosion_mask_01, explosion_mask_02, explosion_mask_03, explosion_mask_04, p38_shrink_1, p38_shrink_2, p38_shrink_3, p38_shrink_4, p38_shrink_mask_1, p38_shrink_mask_2, p38_shrink_mask_3, p38_shrink_mask_4 };
const uint8_t * const enemy_fighter2_images[] PROGMEM = { japanese_enemy_fighter2_N, japanese_enemy_fighter2_NE, japanese_enemy_fighter2_E, japanese_enemy_fighter2_SE, japanese_enemy_fighter2_S, japanese_enemy_fighter2_SW, japanese_enemy_fighter2_W, japanese_enemy_fighter2_NW, zero_mask_N, zero_mask_NE, zero_mask_E, zero_mask_SE, zero_mask_S, zero_mask_SW, zero_mask_W, zero_mask_NW, explosion_01, explosion_02, explosion_03, explosion_04, explosion_mask_01, explosion_mask_02, explosion_mask_03, explosion_mask_04 };
const uint8_t * const enemy_medium_images[] PROGMEM = { enemy_medium, enemy_medium, enemy_medium, enemy_medium, enemy_medium, enemy_medium, enemy_medium, enemy_medium, enemy_medium_mask, enemy_medium_mask, enemy_medium_mask, enemy_medium_mask, enemy_medium_mask, enemy_medium_mask, enemy_medium_mask, enemy_medium_mask, explosion_01, explosion_02, explosion_03, explosion_04, explosion_mask_01, explosion_mask_02, explosion_mask_03, explosion_mask_04 };
#endif

#ifdef PLAYER_JAPANESE
const uint8_t * const player_images[] PROGMEM = { zero_0, zero_1, zero_2, zero_3, zero_4, zero_3, zero_6, zero_1, zero_mask_0, zero_mask_1, zero_mask_2, zero_mask_3, zero_mask_4, zero_mask_3, zero_mask_6, zero_mask_1, explosion_01, explosion_02, explosion_03, explosion_04, explosion_mask_01, explosion_mask_02, explosion_mask_03, explosion_mask_04, zero_shrink_1, zero_shrink_2, zero_shrink_3, zero_shrink_4, zero_shrink_mask_1, zero_shrink_mask_2, zero_shrink_mask_3, zero_shrink_mask_4 };
const uint8_t * const enemy_fighter2_images[] PROGMEM = { us_enemy_fighter2_N, us_enemy_fighter2_NE, us_enemy_fighter2_E, us_enemy_fighter2_SE, us_enemy_fighter2_S, us_enemy_fighter2_SW, us_enemy_fighter2_W, us_enemy_fighter2_NW, us_enemy_fighter2_mask_N, us_enemy_fighter2_mask_NE, us_enemy_fighter2_mask_E, us_enemy_fighter2_mask_SE, us_enemy_fighter2_mask_S, us_enemy_fighter2_mask_SW, us_enemy_fighter2_mask_W, us_enemy_fighter2_mask_NW, explosion_01, explosion_02, explosion_03, explosion_04, explosion_mask_01, explosion_mask_02, explosion_mask_03, explosion_mask_04 };
const uint8_t * const enemy_medium_images[] PROGMEM = { us_enemy_medium, us_enemy_medium, us_enemy_medium, us_enemy_medium, us_enemy_medium, us_enemy_medium, us_enemy_medium, us_enemy_medium, us_enemy_medium_mask, us_enemy_medium_mask, us_enemy_medium_mask, us_enemy_medium_mask, us_enemy_medium_mask, us_enemy_medium_mask, us_enemy_medium_mask, us_enemy_medium_mask, explosion_01, explosion_02, explosion_03, explosion_04, explosion_mask_01, explosion_mask_02, explosion_mask_03, explosion_mask_04 };
#endif

const uint8_t * const enemy_fighter1_images[] PROGMEM = { zero_N, zero_NE, zero_E, zero_SE, zero_S, zero_SW, zero_W, zero_NW, zero_mask_N, zero_mask_NE, zero_mask_E, zero_mask_SE, zero_mask_S, zero_mask_SW, zero_mask_W, zero_mask_NW, explosion_01, explosion_02, explosion_03, explosion_04, explosion_mask_01, explosion_mask_02, explosion_mask_03, explosion_mask_04 };
const uint8_t * const enemy_boat[] PROGMEM = { boat_turrent_N, boat_turrent_NE, boat_turrent_E, boat_turrent_SE, boat_turrent_S, boat_turrent_SW, boat, boat_turrent_NW, boat_turrent_mask, boat_turrent_mask, boat_turrent_mask, boat_turrent_mask, boat_turrent_mask, boat_turrent_mask, boat_mask, boat_turrent_mask, explosion_01, explosion_02, explosion_03, explosion_04, explosion_mask_01, explosion_mask_02, explosion_mask_03, explosion_mask_04 };
